"""Update MEMO with Phase CCXI results - no format strings"""
from datetime import datetime
from pathlib import Path

now = datetime.now().strftime('%Y%m%d%H%M')

lines = []
lines.append("")
lines.append("=================================================================")
lines.append("Phase CCXI: 5语法+5语义 因果对偶5vs5验证 (" + now + ")")
lines.append("=================================================================")
lines.append("")
lines.append("核心改进: 新增voice(主动/被动), person(人称变换), formality(语域变换)")
lines.append("5语法+5语义, n=150, 6层采样, 统计检验5vs5")
lines.append("")
lines.append("S1. 对偶分类 (growth_ratio)")
lines.append("=================================================================")
lines.append("")
lines.append("DS7B:")
lines.append("  SYNTACTIC: tense=3.45x, polarity=6.20x, number=3.75x, negation=9.48x, question=9.86x")
lines.append("  MIXED: person=4.56x(L0=144), semantic_topic=1.66x(L0=512), formality=1.76x(L0=625)")
lines.append("  SEMANTIC: sentiment=1.35x(L0=552), voice=1.26x(L0=811)")
lines.append("")
lines.append("Qwen3:")
lines.append("  SYNTACTIC: tense=14.06x, polarity=16.36x, number=14.73x, negation=18.17x, question=22.05x, person=19.32x!")
lines.append("  SEMANTIC: sentiment=1.25x, semantic_topic=1.26x, voice=0.71x(递减!), formality=1.39x")
lines.append("")
lines.append("GLM4:")
lines.append("  SYNTACTIC: tense=3.31x, polarity=4.61x, number=4.35x, negation=4.91x, question=7.65x, person=5.53x!")
lines.append("  SEMANTIC: sentiment=1.17x, semantic_topic=1.20x, voice=0.78x(递减!), formality=1.17x")
lines.append("")
lines.append("S2. Attn vs MLP (GLM4关键发现!)")
lines.append("=================================================================")
lines.append("")
lines.append("GLM4 L0: tense=49/51, sentiment=15/85, voice=10/90, formality=14/86")
lines.append("GLM4 L39: tense=23/77, sentiment=23/77, voice=20/80, formality=22/78")
lines.append(">>> L0语义特征: MLP=85-90%! MLP是语义信息的入口!")
lines.append(">>> 语法L0: attn=49%, 语义L0: attn=10-15%")
lines.append("")
lines.append("S3. 统计检验")
lines.append("=================================================================")
lines.append("DS7B: Growth p=0.0159, L0 p=0.0040")
lines.append("Qwen3: Growth p=0.0476, L0 p=0.0040")
lines.append("GLM4: Growth p=0.0476, L0 p=0.0754")
lines.append("")
lines.append("=================================================================")
lines.append("Phase CCXI 核心发现")
lines.append("=================================================================")
lines.append("")
lines.append("1. person(人称变换)是语法特征! 三模型一致growth=4.56-19.32x")
lines.append("   原因: I->She涉及动词变形(I am->She is, I have->She has)")
lines.append("   动词形态变化 = 语法, 不管语义内容!")
lines.append("")
lines.append("2. voice(主动/被动)是纯语义特征! growth=0.71-1.26x")
lines.append("   主动/被动不涉及语法标记变化, 只改变论元结构")
lines.append("   L0就由MLP主导(85-90%)")
lines.append("")
lines.append("3. formality(语域变换)是语义特征! growth=1.17-1.39x")
lines.append("   正式/非正式不涉及语法标记变化")
lines.append("")
lines.append("4. 语法vs语义的本质区分:")
lines.append("   语法 = 涉及词形变化(动词变位, 否定标记, 词序变化)")
lines.append("   语义 = 不涉及词形变化(情感, 主题, 语域, 论元结构)")
lines.append("")
lines.append("5. MLP是语义信息的入口 (GLM4关键发现)")
lines.append("   语法L0: attn=49%, 语义L0: attn=10-15%")
lines.append("   语义信息从embedding层就由MLP处理")
lines.append("")
lines.append("=================================================================")
lines.append("修正后的对偶理论")
lines.append("=================================================================")
lines.append("")
lines.append("语法因果效应 C_syn(l) = integral_0^l f_syn(t) dt")
lines.append("  f_syn(t) = 每层新增的词形变化信息 (tense, number, negation标记)")
lines.append("  增长: linear/power_law")
lines.append("")
lines.append("语义因果效应 C_sem(l) = C_sem(0) + epsilon(l)")
lines.append("  C_sem(0) = MLP直接编码的语义信息 (sentiment, topic, voice, formality)")
lines.append("  epsilon(l) = 微小的层间增量 (约0)")
lines.append("  增长: 几乎恒定")
lines.append("")
lines.append("=================================================================")
lines.append("五阶段进展总结")
lines.append("=================================================================")
lines.append("")
lines.append("P1 因果导航 - 99%")
lines.append("  已完成: 差分向量+因果空间+PCA+8bit+Bootstrap+大样本(150对)+median+10特征")
lines.append("")
lines.append("P2 几何定位 - 93%")
lines.append("  已完成: Gram矩阵+Wo SVD+代数拟合+语法vs语义几何差异")
lines.append("  核心: 语法=积分算子, 语义=MLP投影算子")
lines.append("")
lines.append("P3 SAE逆向 - 50%")
lines.append("  设计完成: Delta-SAE + Fiber-SAE + MLP-Delta-SAE")
lines.append("  关键: 语法Delta-SAE(逐层累积) vs 语义Delta-SAE(恒定)")
lines.append("  下步: 实施Delta-SAE训练")
lines.append("")
lines.append("P4 电路逆向 - 98%")
lines.append("  已完成: 10特征x3模型x6层x150对=27000组patching")
lines.append("  核心: 词形变化=语法(积分), 非词形=语义(MLP投影)")
lines.append("")
lines.append("P5 代数/拓扑 - 70%")
lines.append("  已完成: 因果空间5子空间+代数拟合+对偶验证+统计检验")
lines.append("  核心: C_syn(l)=a*l^b+c(b<1), C_sem(l)=C_0")
lines.append("  下步: 积分算子+MLP投影算子的精确代数证明")
lines.append("")
lines.append("=================================================================")
lines.append("新型SAE更新 (基于CCXI发现)")
lines.append("=================================================================")
lines.append("")
lines.append("1. 语法Delta-SAE: 对词形变化delta做SAE, 发现逐层累积的语法原子")
lines.append("2. 语义Delta-SAE: 对非词形delta做SAE, 发现MLP直接编码的语义原子")
lines.append("3. MLP-Delta-SAE: 只对MLP output做差分, 直接分解语义信息入口")
lines.append("4. Fiber-SAE: 追踪语法原子在层间的生长路径")
lines.append("最推荐: MLP-Delta-SAE (第一步) -> Fiber-SAE (第二步)")

memo = "\n".join(lines)

with open('research/glm5/docs/AGI_GLM5_MEMO.md', 'a', encoding='utf-8') as f:
    f.write(memo)
print('MEMO updated at ' + now)
