from stage56_natural_pair_density_curve_link import build_summary, summarize_curve


def test_summarize_curve_extracts_frontier_scalars() -> None:
    curve = [
        {"mass_ratio": 0.10, "compaction_ratio": 0.2, "layer_coverage_ratio": 0.5},
        {"mass_ratio": 0.25, "compaction_ratio": 0.4, "layer_coverage_ratio": 1.0},
        {"mass_ratio": 0.50, "compaction_ratio": 0.8, "layer_coverage_ratio": 1.0},
    ]
    out = summarize_curve(curve)
    assert out["mass10_compaction_ratio"] == 0.2
    assert out["mass25_compaction_ratio"] == 0.4
    assert out["mass50_compaction_ratio"] == 0.8
    assert out["full_layer_coverage_mass_ratio"] == 0.25


def test_build_summary_collects_pair_level_curve_correlations() -> None:
    rows = [
        {
            "model_label": "DeepSeek-7B",
            "category": "fruit",
            "prototype_term": "apple",
            "instance_term": "pear",
            "strict_positive_synergy": True,
            "union_joint_adv": 0.3,
            "union_synergy_joint": 0.2,
            "axes": {
                "logic": {
                    "prototype_mass10_compaction_ratio": 0.2,
                    "instance_mass10_compaction_ratio": 0.3,
                    "pair_mean_mass10_compaction_ratio": 0.25,
                    "prototype_mass25_compaction_ratio": 0.4,
                    "instance_mass25_compaction_ratio": 0.5,
                    "pair_mean_mass25_compaction_ratio": 0.45,
                    "prototype_frontier_sharpness_auc": 0.6,
                    "instance_frontier_sharpness_auc": 0.5,
                    "pair_mean_frontier_sharpness_auc": 0.55,
                    "prototype_knee_mass_ratio": 0.2,
                    "instance_knee_mass_ratio": 0.3,
                    "pair_mean_knee_mass_ratio": 0.25,
                    "prototype_full_layer_coverage_mass_ratio": 0.25,
                    "instance_full_layer_coverage_mass_ratio": 0.30,
                    "pair_mean_full_layer_coverage_mass_ratio": 0.275,
                    "prototype_delta_l2": 3.0,
                    "instance_delta_l2": 2.0,
                    "pair_mean_delta_l2": 2.5,
                    "prototype_delta_mean_abs": 1.0,
                    "instance_delta_mean_abs": 0.8,
                    "pair_mean_delta_mean_abs": 0.9,
                },
                "style": {
                    "prototype_mass10_compaction_ratio": 0.3,
                    "instance_mass10_compaction_ratio": 0.2,
                    "pair_mean_mass10_compaction_ratio": 0.25,
                    "prototype_mass25_compaction_ratio": 0.5,
                    "instance_mass25_compaction_ratio": 0.4,
                    "pair_mean_mass25_compaction_ratio": 0.45,
                    "prototype_frontier_sharpness_auc": 0.2,
                    "instance_frontier_sharpness_auc": 0.3,
                    "pair_mean_frontier_sharpness_auc": 0.25,
                    "prototype_knee_mass_ratio": 0.4,
                    "instance_knee_mass_ratio": 0.5,
                    "pair_mean_knee_mass_ratio": 0.45,
                    "prototype_full_layer_coverage_mass_ratio": 0.4,
                    "instance_full_layer_coverage_mass_ratio": 0.5,
                    "pair_mean_full_layer_coverage_mass_ratio": 0.45,
                    "prototype_delta_l2": 1.0,
                    "instance_delta_l2": 1.2,
                    "pair_mean_delta_l2": 1.1,
                    "prototype_delta_mean_abs": 0.5,
                    "instance_delta_mean_abs": 0.6,
                    "pair_mean_delta_mean_abs": 0.55,
                },
                "syntax": {
                    "prototype_mass10_compaction_ratio": 0.1,
                    "instance_mass10_compaction_ratio": 0.1,
                    "pair_mean_mass10_compaction_ratio": 0.1,
                    "prototype_mass25_compaction_ratio": 0.2,
                    "instance_mass25_compaction_ratio": 0.2,
                    "pair_mean_mass25_compaction_ratio": 0.2,
                    "prototype_frontier_sharpness_auc": 0.7,
                    "instance_frontier_sharpness_auc": 0.6,
                    "pair_mean_frontier_sharpness_auc": 0.65,
                    "prototype_knee_mass_ratio": 0.2,
                    "instance_knee_mass_ratio": 0.2,
                    "pair_mean_knee_mass_ratio": 0.2,
                    "prototype_full_layer_coverage_mass_ratio": 0.3,
                    "instance_full_layer_coverage_mass_ratio": 0.3,
                    "pair_mean_full_layer_coverage_mass_ratio": 0.3,
                    "prototype_delta_l2": 2.5,
                    "instance_delta_l2": 2.4,
                    "pair_mean_delta_l2": 2.45,
                    "prototype_delta_mean_abs": 0.9,
                    "instance_delta_mean_abs": 0.85,
                    "pair_mean_delta_mean_abs": 0.875,
                },
            },
        },
        {
            "model_label": "DeepSeek-7B",
            "category": "fruit",
            "prototype_term": "apple",
            "instance_term": "plum",
            "strict_positive_synergy": False,
            "union_joint_adv": -0.1,
            "union_synergy_joint": -0.2,
            "axes": {
                "logic": {
                    "prototype_mass10_compaction_ratio": 0.6,
                    "instance_mass10_compaction_ratio": 0.7,
                    "pair_mean_mass10_compaction_ratio": 0.65,
                    "prototype_mass25_compaction_ratio": 0.8,
                    "instance_mass25_compaction_ratio": 0.9,
                    "pair_mean_mass25_compaction_ratio": 0.85,
                    "prototype_frontier_sharpness_auc": 0.2,
                    "instance_frontier_sharpness_auc": 0.1,
                    "pair_mean_frontier_sharpness_auc": 0.15,
                    "prototype_knee_mass_ratio": 0.5,
                    "instance_knee_mass_ratio": 0.6,
                    "pair_mean_knee_mass_ratio": 0.55,
                    "prototype_full_layer_coverage_mass_ratio": 0.6,
                    "instance_full_layer_coverage_mass_ratio": 0.7,
                    "pair_mean_full_layer_coverage_mass_ratio": 0.65,
                    "prototype_delta_l2": 1.0,
                    "instance_delta_l2": 1.1,
                    "pair_mean_delta_l2": 1.05,
                    "prototype_delta_mean_abs": 0.4,
                    "instance_delta_mean_abs": 0.45,
                    "pair_mean_delta_mean_abs": 0.425,
                },
                "style": {
                    "prototype_mass10_compaction_ratio": 0.2,
                    "instance_mass10_compaction_ratio": 0.2,
                    "pair_mean_mass10_compaction_ratio": 0.2,
                    "prototype_mass25_compaction_ratio": 0.3,
                    "instance_mass25_compaction_ratio": 0.3,
                    "pair_mean_mass25_compaction_ratio": 0.3,
                    "prototype_frontier_sharpness_auc": 0.3,
                    "instance_frontier_sharpness_auc": 0.2,
                    "pair_mean_frontier_sharpness_auc": 0.25,
                    "prototype_knee_mass_ratio": 0.4,
                    "instance_knee_mass_ratio": 0.4,
                    "pair_mean_knee_mass_ratio": 0.4,
                    "prototype_full_layer_coverage_mass_ratio": 0.4,
                    "instance_full_layer_coverage_mass_ratio": 0.4,
                    "pair_mean_full_layer_coverage_mass_ratio": 0.4,
                    "prototype_delta_l2": 1.1,
                    "instance_delta_l2": 1.0,
                    "pair_mean_delta_l2": 1.05,
                    "prototype_delta_mean_abs": 0.45,
                    "instance_delta_mean_abs": 0.4,
                    "pair_mean_delta_mean_abs": 0.425,
                },
                "syntax": {
                    "prototype_mass10_compaction_ratio": 0.5,
                    "instance_mass10_compaction_ratio": 0.5,
                    "pair_mean_mass10_compaction_ratio": 0.5,
                    "prototype_mass25_compaction_ratio": 0.7,
                    "instance_mass25_compaction_ratio": 0.7,
                    "pair_mean_mass25_compaction_ratio": 0.7,
                    "prototype_frontier_sharpness_auc": 0.1,
                    "instance_frontier_sharpness_auc": 0.1,
                    "pair_mean_frontier_sharpness_auc": 0.1,
                    "prototype_knee_mass_ratio": 0.6,
                    "instance_knee_mass_ratio": 0.6,
                    "pair_mean_knee_mass_ratio": 0.6,
                    "prototype_full_layer_coverage_mass_ratio": 0.6,
                    "instance_full_layer_coverage_mass_ratio": 0.6,
                    "pair_mean_full_layer_coverage_mass_ratio": 0.6,
                    "prototype_delta_l2": 1.0,
                    "instance_delta_l2": 1.0,
                    "pair_mean_delta_l2": 1.0,
                    "prototype_delta_mean_abs": 0.4,
                    "instance_delta_mean_abs": 0.4,
                    "pair_mean_delta_mean_abs": 0.4,
                },
            },
        },
    ]
    summary = build_summary(rows)
    assert summary["joined_pair_count"] == 2
    assert summary["axis_row_count"] == 6
    assert summary["top_abs_correlations"]
